import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>{title ? title + ' - JBShop' : 'JBShop'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col justify-between ">
        <header className="text-gray-600 body-font shadow-md">
          <div className="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
            <Link
              href="/"
              className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                className="w-10 h-10 text-white p-2 bg-yellow-500 rounded-full"
                viewBox="0 0 24 24"
              >
                <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" />
              </svg>
              <span className="ml-3 text-xl">Tailblocks</span>
            </Link>
            <nav className="md:ml-auto flex flex-wrap items-center text-base justify-center">
              <Link href={'/cart'} className="mr-5 hover:text-gray-900 ">
                Cart
              </Link>
              <Link href={'/login'} className="mr-5 hover:text-gray-900">
                Log In
              </Link>
            </nav>
          </div>
        </header>

        <main className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          {children}
        </main>
        <footer className="flex h-10 justify-center items-center shadow-inner">
          <p>Copyright ©2023 JBShop</p>
        </footer>
      </div>
    </>
  );
}

export default Layout;
